name: Backwards Compatibility Tests

on: ["workflow_dispatch", "pull_request"]

jobs:
  compatibility_test:
    strategy:
      matrix:
        clojure_version: ['1.8.0', '1.9.0', '1.10.0', '1.11.0', '1.12.0']

    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ matrix.clojure_version }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.2.0

    - name: Print concurrency group
      run: echo '${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}'

    - name: Cache maven dependencies
      uses: actions/cache@v4
      env:
          cache-name: cache-maven
      with:
          path: ~/.m2
          save-always: true
          key: ${{ runner.os }}-clj-${{ hashFiles('**/project.clj') }}
          restore-keys: |
            ${{ runner.os }}-clj

    - name: Install Clojure Dependencies
      run: lein deps

    - name: Override Clojure Version
      run: lein change :dependencies:org.clojure/clojure set '"${{ matrix.clojure_version }}"'

    - name: Run all tests
      run: lein test

