name: Generate Contributors Image
on:
  schedule:
    - cron: '0 3 * * 0' # At 03:00 on Sunday.
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.WALL_BREW_BOT_PAT }}
          svgPath: CONTRIBUTORS.svg
          affiliation: all
