name: Label Pull Requests
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.2
      with:
        repo-token: "${{ secrets.WALL_BREW_BOT_PAT }}"
