name: Linter
on: [pull_request]

jobs:
  spell-check:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}

      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
          reporter: github-pr-review
          filter_mode: file

  clj-kondo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}

      - name: Install clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2021.06.01'

      - name: Lint Clojure
        run: |
          clj-kondo --config ./dev/lint/clj-kondo.edn --lint \
            $(find . -type f -regex ".*\.clj[csx]?$")
